[env]
LEPTOS_TAILWIND_VERSION="v4.1.18"
LEPTOS_WASM_OPT_VERSION="version_125"

[tasks.dev-mac]
run_task = { name = ["dev-server-mac", "dev-caddy"], parallel = true }

[tasks.dev-server-mac]
dependencies = ["kill-qvis-app"]
command = "cargo"
args = ["leptos", "watch"]

[tasks.dev-server-mac.env]
DYLD_FALLBACK_LIBRARY_PATH="/usr/local/lib:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/"
LDFLAGS="-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
LD_LIBRARY_PATH="/usr/local/lib"

[tasks.dev-caddy]
command = "caddy"
args = ["reverse-proxy", "--to", ":3000"]

[tasks.prod]
dependencies = ["kill-qvis-app"]
command = "cargo"
args = ["leptos", "serve"]

[tasks.kill-qvis-app]
command = "pkill"
args = ["qvis_app"]
ignore_errors = true

[config]
unstable_features = ["CTRL_C_HANDLING"]
